[package]
name = "fez-test"
version = "0.1.0"
authors = ["Alexandra E. Vidal <delta.psi00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glutin = "0.24.0"
