[package]
name = "fez-test"
version = "0.1.0"
authors = ["Alexandra E. Vidal <delta.psi00@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
glutin = "0.24.0"
cgmath = "0.17.0"
pix = "0.13.0"
png = "0.16.3"
bitflags = "1.2.1"
